export const AUTHENTICATE_USER = 'AUTHENTICATE_USER:';
export const REMOVE_USER = 'REMOVE_USER:';
export const SHOW_PROPOSALS = 'SHOW_PROPOSALS';
export const ADD_CURRENT_POSITION = 'ADD_CURRENT_POSITION';
